apiVersion: apps/v1
kind: Deployment
metadata:
  name: elvish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elvish
  template:
    metadata:
      labels:
        app: elvish
    spec:
      containers:
      - image: theelves/elvish
        name: elvish
        command:
        - /bin/sh
        - -c
        args: 
        - |
          apk add bash figlet
          curl https://get.k0s.io/install.sh | sh
          ~/.k0s/bin/k0s agent -tags 'Elvish' -name elvish -cmd "while :; do figlet elvish; elvish; sleep 1; done"
        resources: {}
        securityContext:
          runAsUser: 0
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always
