apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: k0s-webcli
  name: k0s-webcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k0s-webcli
  template:
    metadata:
      labels:
        app: k0s-webcli
    spec:
      containers:
      - image: btwiuse/k0s:latest
        name: k0s-webcli
        command:
        - bash
        - -c
        args: 
        - |
          apk add tmux
          curl https://get.k0s.io/install.sh | bash
          tmux new-session -d cat; tmux set -g status off
          ~/.k0s/bin/k0s agent -tags "k0s webcli" -cmd "while :; do tmux new-session ~/.k0s/bin/k0s; done"
      restartPolicy: Always
