apiVersion: v1
kind: ServiceAccount
metadata:
  name: k9s-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k9s-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k9s-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k9s-clusterrole
subjects:
- kind: ServiceAccount
  name: k9s-serviceaccount
  namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: k9s
  name: k9s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k9s
  template:
    metadata:
      labels:
        app: k9s
    spec:
      containers:
      - image: derailed/k9s
        name: k9s
        command:
        - sh
        - -c
        args: 
        - |
          apk add curl bash tmux
          curl https://get.k0s.io/install.sh | bash
          tmux new-session -d cat; tmux set -g status off
          ~/.k0s/bin/k0s agent -verbose -tags "k9s on k0s" -cmd 'while :; do reset; tmux new-session env TERM=xterm-256color k9s; sleep 1; done'
      restartPolicy: Always
      serviceAccountName: k9s-serviceaccount

