apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - image: alpine
        name: login
        command:
        - /bin/sh
        - -c
        args: 
        - |
          apk add bash curl figlet
          curl https://get.k0s.io/install.sh | bash
          (echo admin; echo admin) | adduser admin
          ~/.k0s/bin/k0s agent -tags 'login' -name login -cmd "while :; do figlet login; login; sleep 1; done"
        resources: {}
        securityContext:
          runAsUser: 0
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always
