apiVersion: apps/v1
kind: Deployment
metadata:
  name: powershell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powershell
  template:
    metadata:
      labels:
        app: powershell
    spec:
      containers:
      - image: microsoft/powershell
        name: powershell
        command:
        - /bin/bash
        - -c
        args: 
        - |
          apt update; apt install -y figlet
          curl https://get.k0s.io/install.sh | bash
          ~/.k0s/bin/k0s agent -tags 'PowerShell/Linux' -name powershell -cmd "while :; do figlet powershell; pwsh; sleep 1; done"
        resources: {}
        securityContext:
          runAsUser: 0
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always
