apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swift
  template:
    metadata:
      labels:
        app: swift
    spec:
      containers:
      - image: swift
        name: swift
        command:
        - /bin/bash
        - -c
        args: 
        - |
          apt update; apt install -y figlet curl
          curl https://get.k0s.io/install.sh | bash
          ~/.k0s/bin/k0s agent -tags 'swift' -name swift -cmd "while :; do figlet swift; swift; sleep 1; done"
        resources: {}
        securityContext:
          runAsUser: 0
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always
