apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaegi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaegi
  template:
    metadata:
      labels:
        app: yaegi
    spec:
      containers:
      - image: yaegi/yaegi
        name: yaegi
        command:
        - /bin/sh
        - -c
        args: 
        - |
          apk --upgrade add bash figlet curl
          curl https://get.k0s.io/install.sh | bash
          ~/.k0s/bin/k0s agent -tags 'yaegi' -name yaegi -cmd "while :; do figlet yaegi; yaegi; sleep 1; done"
        resources: {}
        securityContext:
          runAsUser: 0
        imagePullPolicy: Always
      dnsPolicy: ClusterFirst
      restartPolicy: Always
